### ISSUE TITLE
A link that shows raw text of the note

### ISSUE THREAD

**Issue by WofWca** [cupcakearmy/cryptgeon#142]
Hello and thanks for the awesome software!

I had an idea that is useful for automation software.
And that is, after making a note, to have an option to copy a link that, when followed, will show the raw (plain) text of the note without any wrapper HTML.
Of course, this means that there is not going to be any button to confirm that you want to open the note, but that is not needed for automation software.

Of course you have to consider that it might confuse the users, So perhaps this could be put behind the advanced thing when creating a node Instead of adding this to the screen that appears when you have already made the note.

**Comment by cupcakearmy** [comment]
Interesting idea :) 
Right now, some kind of browser is needed, since the decryption is client side, so the server cannot directly decrypt and send the contents. 
However, there is the [CLI](https://github.com/cupcakearmy/cryptgeon/blob/main/packages/cli/README.md). Will close it in favour of the CLI, feel free to reopen if i misunderstood :)
