### ISSUE TITLE
dead-mans switch

### ISSUE THREAD

**Issue by noveoko** [cupcakearmy/cryptgeon#78]
## Feature Request

# Future Publication Date

Instead of allowing the user to only set an expiration date, allow the user to set a publication date. In this case a user that wants a note to be available to anyone, but only in X days, would be able to use this to publicly release a note at their discretion regardless of their state (dead/alive).

I see lot's of uses for this as a **dead-mans switch**.

Potential users:
* Journalists
* Whistleblowers

Scenario:
1. User is sent on a dangerous mission
2. User creates a note to expire 1 year after the start of the mission
3. User sends the link to the note to family and friends
4. Family and friends cannot read the note until the time has passed.

**Comment by cupcakearmy** [comment]
Very cool idea. I assume it would require the ability to unsed it though right?

**Comment by noveoko** [comment]
My idea for that is to use multi-parting voting. This would require some effort, but essentially the message could be reversed but only in cases where 3 out of 5 trusted parties (added at message creation) would vote to reverse the send.

My main use case for this is journalists, or whistleblowers that want it to be clear that they cannot reverse such a message once it has been sent.

**Comment by cupcakearmy** [comment]
I have a feeling this is way outside the scope of this project.
There are some fundamentals barriers for this:

1. Data is in ram, and as stated when creating a note, it is not guarateed to be available in the future. It could be evicted at any moment. This would require work on making the note not evicatable and persistent.
2. The backend contains very little logic, this is by design. Requiring trusted parties, codes, and so on is a lot of code in comparison to the current state, which I'm not sure makes sense.

So for now I believe this is a wont-do. If you feel brave, of course, go for it, but realistically I won't implement it.
Thanks for the suggestions though!
