### ISSUE TITLE
关于上传的建议（Suggestions on uploading）

### ISSUE THREAD

**Issue by x2358473** [cupcakearmy/cryptgeon#91]
首先非常感谢你们的付出，我是一个中文国家，英语不是太好
First of all, thank you very much for your efforts，I'm from a Chinese country, and my English is not very good.

我在在使用过程中发现关于上传文件的一个小问题
I found a small problem about uploading files during use.

 “SIZE_LIMIT” 虽然可以进行限制文件大小，但这是上传后才去判断，如果有人恶意上传大文件，那么我的服务器带宽将会被占满，
"SIZE_LIMIT" Although the file size can be limited, it can only be judged after uploading. If someone maliciously uploads large files, my server bandwidth will be full.

能不能在前端做一个限制，如果选择的文件超过 “SIZE_LIMIT” 不进行创建
Can you make a limit at the front end? If the selected file exceeds "SIZE_LIMIT", it will not be created.

**Comment by cupcakearmy** [comment]
Hey,

I'll include a translated version below, but with no guarantees.


The point you are making is a valid consern. The size of the file is checked by server. This works because each request states a given payload size. If this payload size is malicious, the attacker simply will not upload the hole file, but just a portion of it.


Having a check on the frontend is mostly a cosmetic touch, as if your are an attacker, you don't need to use the frontend, you could simlpy just attack the backend directly and the limits in the frontend would not stop you.


Hope that clarified things a bit :)

---

嘿、
我将在下面附上一个翻译版本，但不能保证。

你所提出的问题是一个有效的问题。文件的大小是由服务器检查的。这样做是因为每个请求都说明了一个给定的有效载荷大小。如果这个有效载荷的大小是恶意的，攻击者就不会上传孔文件，而只是上传其中的一部分。

在前台进行检查主要是一种装饰，因为如果你是一个攻击者，你不需要使用前台，你可以直接攻击后台，前台的限制不会阻止你。

希望这能让你明白一些事情 :)

**Comment by x2358473** [comment]
@cupcakearmy 
我赞同你的观点，服务端任何时候都是要进行校验的。因为前端的一切都不可信。
I agree with you that the server needs to be verified at any time. Because everything at the front end is not credible.

但是如果是有技术的攻击者，他们可以通过api上传大量的小文件来攻击，完全可以绕过“SIZE_LIMIT”限制。除非你在服务端有相对应的风控。比如规定时间内上传次数等。否则也同样能被有技术的攻击人员攻击。
But if there are technical attackers, they can attack by uploading a large number of small files in api, which can completely bypass the "SIZE_LIMIT" limit. Unless you have the corresponding risk control on the server. For example, the number of uploads within the specified time. Otherwise, it can also be attacked by skilled attackers.

我所希望前端限制是为了大部份的普通用户的。
I hope the front-end limit is for most ordinary users.

目前我个人觉得存在的问题有两个：
At present, I personally think there are two problems:

1. 当前的前端界面在上传文件时没有显示所选择的文件大小，只有上传后服务端返回超过“SIZE_LIMIT”限制，用户才知道这个文件在太大了。这种是正常用户的不友好体验。
1. The current front-end interface does not show the selected file size when uploading the file. Only when the server returns after uploading exceeds the "SIZE_LIMIT" limit, the user knows that the file is too large. This is an unfriendly experience for normal users.

2. 有些用户就是一些小恶意，上传一个5GiB的电影，那么会让服务一直在接收这个文件。直到接收完报错了，才会告知用户你这个操作无效。这会如果有正常用户在使用。可能会被这个5GiB的文件给占用了带宽导致变的可能失败或都一直等待中
2. Some users are just a little malicious, uploading a 5GiB movie, which will make the service receive the file all the time. The user will not be informed that this operation is invalid until the error is reported. This will be used by normal users. The bandwidth may be occupied by this 5GiB file, which may fail or wait all the time.

以上只是我提的一点建议。您可以只当做一点参考，不用太当回事。
The above is just one of my suggestions. You can just take it as a reference, don't take it too seriously.
